apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Name }}-pvc
spec:
  storageClassName: {{ .Values.Name }}-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageclaim }}
