apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.Name }}-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
